config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  ########################################################################################################
  
  namespace :dashboard do
    
    controller :pages do
      get '/home' => :home
      get '/email' => :email
      get '/perfil' => :perfil
      get '/settings' => :settings
      post '/save_settings' => :save_settings
    end
    
    controller :users do
    end
    resources :users
    
    controller :authors do
    end
    resources :authors
    
    controller :books do
      get '/books/get_authors' => :get_authors, as: :books_get_authors
      get '/books/get_book' => :get_book, as: :books_get_book
    end
    resources :books
    
    controller :completeds do
    end
    resources :completeds
    
    mount ActionCable.server => '/dashboard/cable'
    
    controller :cycles do
      get '/cycles/channels/:id' => :channels, as: :cycles_channels
      get '/cycles/members/:id' => :members, as: :cycles_members
    end
    resources :cycles
    
    controller :channels do
      get '/channels/scroll/:id' => :scroll, as: :channels_scroll
    end
    resources :channels, only: [:show, :create, :destroy]
    
    controller :talks do
      get '/talks/scroll/:id' => :scroll, as: :talks_scroll
    end
    resources :talks, only: [:show]
    
    controller :tests do
      post '/tests/complete/:id' => :complete, as: :tests_complete
    end
    resources :tests 
    
    get '/:slug', to: 'cycles#show'
    resources :participations, only: [:create, :destroy]

  	root 'pages#home'
  	get '*path' => redirect('/')
  end

  ########################################################################################################


  devise_for :users, path: '', path_names: { sign_in: 'home', sign_out: 'logout', sign_up: "register"}

  authenticated :user do
  	root 'dashboard/pages#home', as: :authenticated_root
  end

  controller :pages do
  	get '/home' => :home
  	post '/login' => :login
  end

  root "pages#home"  
  get '*path' => redirect('/')

end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ActionController::Base
	before_action :authenticate_user!
	protect_from_forgery with: :exception
	before_action :store_user_location!, if: :storable_location?
	rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
	
	layout 'dashboard'


	rescue_from CanCan::AccessDenied do |exception|
	  respond_to do |format|
	    format.json { head :forbidden, content_type: 'text/html' }
	    format.html { redirect_to main_app.root_url, alert: exception.message }
	  end
	end

	private

	def record_not_found
		flash[:alert] = "Você está tentando acessar algo que não existe."
		redirect_back(fallback_location: root_url)
	end

	def storable_location?
		request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
	end

	def store_user_location!
	  # :user is the scope we are authenticating
	  store_location_for(:user, request.fullpath)
	end

  def after_sign_out_path_for(resource_or_scope)
  	stored_location_for(resource_or_scope) || super
  end




  end

app/controllers/dashboard/authors_controller.rb
class Dashboard::AuthorsController < Dashboard::ApplicationController

  before_action :set_author, only: [:show, :edit, :update, :destroy]

	def index
    authorize! :config, :backend
		conditions = []
		conditions << "authors.id IN (#{params[:id].split(/\W+/).uniq.join(', ')})" unless params[:id].blank?
		conditions << "UPPER(unaccent(authors.name)) LIKE '%#{I18n.transliterate(params[:name].upcase)}%'" unless params[:name].blank?
		@authors = Author.where(conditions.join(" AND ")).order("created_at desc")
	end

	def show
	end

	def edit
	end

	def update
    authorize! :config, :backend
		if @author.update(author_params)
			if params[:author][:fotos].blank?
				respond_to do |format|
					format.js {render inline: "M.toast({html: 'Updated!', classes: 'green'}); " }
				end
			else
				redirect_to request.referrer, notice: "Updated"
			end
		else
			respond_to do |format|
				format.js {render inline: "M.toast({html: '#{@author.errors.messages}', classes: 'red'}); " }
			end
		end
	end

	def new
		@author = Author.new
	end

	def create
    authorize! :config, :backend
		@author = Author.new(author_params)
		if @author.save
			redirect_to edit_dashboard_author_path(id: @author.id), notice: "Author #{@author.name} created successfully!"
		else
			respond_to do |format|
				format.js
			end
		end
	end

	def destroy
    authorize! :config, :backend
		name = @author.name
		if @author.books.size == 0 and @author.destroy
			redirect_to request.referrer, notice: "#{name} has been deleted!"
		else
			respond_to do |format|
				format.js {render inline: "M.toast({html: 'Unable to delete author #{@author.name}', classes: 'red'}); " }
			end
		end
	end

	private

	def author_params
		params.require(:author).permit(:name, :description, :biography)
	end
	def set_author
		@author = Author.find(params[:id])
	end

end

app/controllers/dashboard/books_controller.rb
class Dashboard::BooksController < Dashboard::ApplicationController

	require './app/services/book_service'
  before_action :set_book, only: [:show, :edit, :update, :destroy]

	def index
    authorize! :config, :backend
		conditions = []
		conditions << "books.id IN (#{params[:id].split(/\W+/).uniq.join(', ')})" unless params[:id].blank?
		@books = Book.where(conditions.join(" AND ")).order("created_at desc")
	end

	def get_authors
		conditions = []
		conditions << "UPPER(unaccent(authors.name)) LIKE '%#{I18n.transliterate(params[:name].upcase)}%'"

		@authors = Author.where(conditions.join(' AND ')).order("name asc")
	end

	def get_book
		@list = {}
		@list = BookService.get_book(params[:title])
		@features = @list.blank? ? {} : @list[:features]
		session[:features] = @features

	end

	def show
		@cycle = @book.cycles.first
	end

	def edit
		@features = @book.features
	end

	def update
    authorize! :config, :backend
		if @book.update(book_params)
			if params[:book][:fotos].blank?
				respond_to do |format|
					format.js {render inline: "M.toast({html: 'Updated!', classes: 'green'}); " }
				end
			else
				redirect_to request.referrer, notice: "Updated"
			end
		else
			respond_to do |format|
				format.js {render inline: "M.toast({html: '#{@book.errors.messages}', classes: 'red'}); " }
			end
		end
	end

	def new
		@book = Book.new
		session.delete(:features)
	end

	def create
    authorize! :config, :backend
		@book = Book.new(book_params)

		unless session[:features].blank?
			@book.features = session[:features] 
			session.delete(:features)
		end

		Book.transaction do
			author_name = params[:author].gsub(',', ' ').gsub(';', ' & ').gsub('  ', ' ')

			unless author_name.include?"&"
				first = author_name.split(/ /).first
				author_name = author_name.gsub("#{first}","")
				author_name += " #{first}"
			end

			unless author_name.blank? or @book.valid?
				author = Author.where("UPPER(unaccent(authors.name)) LIKE '%#{I18n.transliterate(author_name.upcase)}%'").first_or_create do |a|
					a.name = author_name
				end
				@book.author_id = author.id
			end 

			if @book.save
				redirect_to edit_dashboard_book_path(id: @book.id), notice: "Book #{@book.name} created successfully!"
			else
				respond_to do |format|
					format.js
				end
			end
		end
	end

	def destroy
    authorize! :config, :backend
		title = book.name
		if @book.cycles.size == 0 and @book.destroy
			redirect_to request.referrer, notice: "#{title} has been deleted!"
		else
			respond_to do |format|
				format.js {render inline: "M.toast({html: 'Unable to delete book #{@book.name}', classes: 'red'}); " }
			end
		end
	end

	private

	def book_params
		params.require(:book).permit(:name, :description, :author_id, :link, :scraping, :image, {features: []})
	end
	def set_book
		@book = Book.find(params[:id])
	end

end

app/controllers/dashboard/channels_controller.rb
class Dashboard::ChannelsController < Dashboard::ApplicationController
  before_action :set_channel, only: [:destroy, :show, :scroll]

  def create
    @channel = Channel.new(channel_params)
    authorize! :create, @channel

    respond_to do |format|
      if @channel.save
        format.json { render :show, status: :created }
      else
        Rails.logger.debug("  ============== Exception:  #{@channel.errors.full_messages} ")

        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @channel
    @channel.destroy

    respond_to do |format|
      format.json { render json: true }
    end
  end

  def show
    session[:per_page] = 1
    authorize! :read, @channel
  end

  def scroll
    session[:per_page] += 1 unless session[:per_page] > @channel.messages.page.total_pages 
    authorize! :read, @channel
  end

  private

  def set_channel
    @channel = Channel.find(params[:id])
  end

  def channel_params
    params.require(:channel).permit(:slug, :cycle_id).merge(user: current_user)
  end
end

app/controllers/dashboard/chats_controller.rb
class Dashboard::ChatsController < Dashboard::ApplicationController

    def show
    	@comments = Comment.all
    end

end

app/controllers/dashboard/completeds_controller.rb
class Dashboard::CompletedsController < Dashboard::ApplicationController

  before_action :set_completed, only: [:show, :edit, :update, :destroy]

	def index
		conditions = []
		conditions << "completeds.id IN (#{params[:id].split(/\W+/).uniq.join(', ')})" unless params[:id].blank?
		conditions << "UPPER(unaccent(completeds.name)) LIKE '%#{I18n.transliterate(params[:name].upcase)}%'" unless params[:name].blank?
		@completeds = Completed.where(conditions.join(" AND ")).order("created_at desc")
	end

	def show
	end

	def edit
	end

	def update
		if @completed.update(completed_params)
			respond_to do |format|
				format.js {render inline: "M.toast({html: 'Updated!', classes: 'green'}); " }
			end
		else
			respond_to do |format|
				format.js {render inline: "M.toast({html: '#{@completed.errors.messages}', classes: 'red'}); " }
			end
		end
	end

	def new
		@completed = Completed.new
	end

	def create
		@completed = Completed.new(completed_params)
		if @completed.save
			respond_to do |format|
				format.js {render inline: "M.toast({html: 'Created!', classes: 'green'}); " }
			end
		else
			respond_to do |format|
				format.js
			end
		end
	end

	def destroy
		name = @completed.name
		if @completed.books.size == 0 and @completed.destroy
			redirect_to request.referrer, notice: "#{name} has been deleted!"
		else
			respond_to do |format|
				format.js {render inline: "M.toast({html: 'Unable to delete completed #{@completed.name}', classes: 'red'}); " }
			end
		end
	end

	private

	def completed_params
		params.require(:completed).permit(:content).merge(completed_date: Date.today)
	end
	def set_completed
		@completed = Completed.find(params[:id])
	end

end

app/controllers/dashboard/cycles_controller.rb
class Dashboard::CyclesController < Dashboard::ApplicationController

  before_action :set_cycle, only: [:show, :edit, :update, :destroy, :channels, :members]

	def index
    authorize! :config, :backend
		conditions = []
		conditions << "cycles.id IN (#{params[:id].split(/\W+/).uniq.join(', ')})" unless params[:id].blank?
		@cycles = Cycle.where(conditions.join(" AND ")).order("created_at desc")
	end

	def channels
	end

	def members
		@users = @cycle.users
	end

	def show
		authorize! :read, @cycle
	end

	def edit
	end

	def update
    authorize! :config, :backend
		respond_to do |format|
			if @cycle.update(cycle_params)
      	@cycle.ordenar!
					format.js {render inline: "M.toast({html: 'Updated!', classes: 'green'}); " }
			else
					format.js {render inline: "M.toast({html: '#{@cycle.errors.messages}', classes: 'red'}); " }
			end
		end
	end

	def new
		@cycle = Cycle.new
	end

	def create
    authorize! :config, :backend
		@cycle = Cycle.new(cycle_params)
		if @cycle.save
      @cycle.ordenar!
			redirect_to edit_dashboard_cycle_path(id: @cycle.id), notice: "Cycle about #{@cycle.book.name} created successfully!"
		else
			respond_to do |format|
				format.js
			end
		end
	end

	def destroy
    authorize! :config, :backend
		title = @cycle.slug
		if @cycle.participations.size < 0 and  @cycle.destroy
			redirect_to request.referrer, notice: "#{title} has been deleted!"
		else
			respond_to do |format|
				format.js {render inline: "M.toast({html: 'Unable to delete cycle about #{@cycle.book.name}', classes: 'red'}); " }
			end
		end
	end

	private

	def set_by_slug_cycle
		@cycle = Cycle.find_by(slug: params[:slug])
	end

	def cycle_params
		params.require(:cycle).permit(:description, :book_id, :start_date, :end_date, :slug, :notes, :links).merge(user: current_user)
	end
	def set_cycle
		@cycle = Cycle.find(params[:id])
	end

end

app/controllers/dashboard/pages_controller.rb
class Dashboard::PagesController < Dashboard::ApplicationController
	
	def home
	end

	def email
		@user = current_user
		@cycle = Cycle.first
	end

	def settings
    authorize! :config, :backend
	end

	def save_settings
    authorize! :config, :backend
		Setting.email_confirmation_commitment_subject										= params[:email_confirmation_commitment_subject]
		Setting.email_confirmation_commitment														= params[:email_confirmation_commitment]
		Setting.email_activity_completion_subject												= params[:email_activity_completion_subject]
		Setting.email_activity_completion																= params[:email_activity_completion]
		Setting.email_activity_deadline_coming_end_subject							= params[:email_activity_deadline_coming_end_subject]
		Setting.email_activity_deadline_coming_end											= params[:email_activity_deadline_coming_end]
		
		respond_to do |format|
			format.js {render inline: "M.toast({html: 'Updated!', classes: 'green'}); " }
		end
	end

end

app/controllers/dashboard/participations_controller.rb
class Dashboard::ParticipationsController < Dashboard::ApplicationController
  before_action :set_participation, only: [:destroy]

  def create
    @participation = Participation.new(participation_params)

      if @participation.save
        SendMailer.email_confirmation_commitment(current_user, @participation.cycle).deliver_later
        redirect_to dashboard_cycle_path(@participation.cycle), notice: "Joined to #{@participation.cycle.slug}!"
      else
        respond_to do |format|
        end
      end
  end

  def destroy
    authorize! :destroy, @participation
    @participation.destroy

    respond_to do |format|
      format.json { render json: true }
    end
  end

  private

  def set_participation
    @participation = Participation.find_by(user_id: params[:id], cycle_id: params[:cycle_id])
  end

  def participation_params
    params.require(:participation).permit(:cycle_id).merge(user_id: current_user.id)
  end
end

app/controllers/dashboard/talks_controller.rb
class Dashboard::TalksController < Dashboard::ApplicationController
	before_action :set_talk, only: [:show]

	def show
		authorize! :read, @talk
	end

	private

def set_talk
    @talk = Talk.find_by(user_one_id: [params[:id], current_user.id], user_two_id: [params[:id], current_user.id], cycle: params[:cycle_id])
    # If talk not yet created
    unless @talk
      @cycle = Cycle.find(params[:cycle_id])
      @user = User.find(params[:id])
      # Check if current_user and user are cycle members
      if @cycle.my_users.include? current_user and @cycle.my_users.include? @user
        @talk = Talk.create(user_one: current_user, user_two: @user, cycle: @cycle)
      end
    end
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
		conditions = []
		conditions << "users.id IN (#{params[:id].split(/\W+/).uniq.join(', ')})" unless params[:id].blank?
		@users = User.where(conditions.join(" AND ")).order("created_at desc")
	end

	def show
	end

	def edit
	end

	def update
    params[:user].delete(:password) if params[:user][:password].blank?
		if @user.update(user_params)
			if params[:user][:fotos].blank?
				respond_to do |format|
					format.js {render inline: "M.toast({html: 'Updated!', classes: 'green'}); " }
				end
			else
				redirect_to request.referrer, notice: "Updated"
			end
		else
			respond_to do |format|
				format.js {render inline: "M.toast({html: '#{current_user.errors.messages}', classes: 'red'}); " }
			end
		end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to edit_dashboard_user_path(id: @user.id), notice: "User #{@user.name} created successfully!"
		else
			respond_to do |format|
				format.js
			end
		end
	end

	def destroy
		if @user.destroy
			redirect_to request.referrer, notice: "Usuário deletado!"
		else
			respond_to do |format|
				format.js {render inline: "M.toast({html: 'Unable to delete user #{@user.name}', classes: 'red'}); " }
			end
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :phone)
	end
	def set_user
		@user = User.find(params[:id])
	end

end

app/views/dashboard/pages/email.html.erb
<div style="margin: 0% 15%;">
	<%= "#{raw Setting.email_confirmation_commitment}".gsub("@user", @user.name).gsub("@cycle", @cycle.slug).html_safe %>
</div>

app/views/dashboard/pages/home.html.erb
<div class="container-fluid">
	

	<div class="row">
		<% actual_cycles.each do |cycle| %>
			<div class="col s12 m6 l4">
	      		<div class="card animated zoomInDown" style="min-height: 400px;" >
	        		<div class="card-image">
						<img src="<%= cycle.book.image.blank? ? '/images/missing.jpg' : cycle.book.image.gsub('amp;','') %>" style="width: 100%; height: auto; ">
					</div>
	      		</div>
			</div>
			<div class="col s12 m6 l8">
				<ul id="right_content" class="collection animated zoomIn">
			        <li class="collection-header margin-left-15 "><h5 class="orange-text f25"><%= "#{cycle.id}º cycle" %></h5></li>
					<li class="collection-item animated zoomInRight delay-300">
						<strong>Book: </strong>
						<span class="span">
							<%= book_name cycle.book %>
						</span>
						<br>
						<% unless book_link(cycle.book).blank? %>
							<a href="<%= book_link cycle.book %>" target="_blank">Link</a> 
						<% end %>
						<br><br>
						<strong>Description: </strong>
					<span class="span">
						<%= book_description(cycle.book) %>
						<br><br>
					</span>
						<strong>Author:</strong>
						<span class="span">
							<%= author_name cycle.book.author %>
						</span>
					</li>
					<li class="collection-item animated zoomInRight delay-400">
					<span class="span">
						<strong>description: </strong> <%= cycle_description cycle %>
					</span>
					<br><br>
					<span class="span">
						<strong>duration: </strong> <%= cycle_period cycle %>
					</span>
					</li>
					<li class="collection-item animated zoomInRight delay-500">
						<div class="row no-margin">
							<div class="col s12 m6 l6">
								<strong>Participations: </strong> 
								<span class="span">
									<%= link_to "#{cycle.participations.size}", "", class: "btn blue shadow" %>
								</span>
							</div>
							<% unless cycle_joined cycle %>
								<div class="col s12 m6 l6">
									<a id="set_participation" code="<%= cycle.id %>" class="btn shadow green right">Participar</a>
								</div>
							<% end %>
						</div>
					</li>
					<% if cycle_joined cycle %>
						<li class="collection-item animated zoomInRight delay-600">
							<div class="row no-margin">
								<div class="col s12 m6 l6">
									<%= link_to "<i class='material-icons blue-text'>thumb_up</i>".html_safe, "", class: "btn btn-floating white shadow-off" %>
									<%= link_to "<i class='material-icons blue-text'>thumb_down</i>".html_safe, "", class: "btn btn-floating white shadow-off" %>
								</div>
								<div class="col s12 m6 l6">
									<p class="right cursor">
										<%= link_to "channels", dashboard_cycles_channels_path(cycle), method: "get", class: "peso-6 f20" %>
										&nbsp;&nbsp;&nbsp;&nbsp;
										<%= link_to dashboard_cycle_path(cycle) do %>
											<span class="span blue-text f20 peso-6">let's do it</span>
										<% end %>
									</p>
								</div>
							</div>
						</li>
					<% end %>
				</ul>

			</div>
		<% end %>
	</div>
</div>


<script type="text/javascript">

	$("#set_participation").click(function(){
		var cycle = $(this).attr("code");
		$.ajax({
			url: "/dashboard/participations",
			type: "POST",
			dataType: "script",
			data: {
				'participation': {
					'cycle_id': 			cycle
				}
			} 
		});
	});
</script>

app/views/dashboard/pages/perfil.html.erb
<div class="container">
	<br>
	<h5 class="blue-text">Editing Current User - <%= current_user.name %></h5>
	<br>
	<%= form_for [:dashboard, current_user], remote: true do |f| %>
		<div class="row">
			<div id="form_error"></div>

			<div class="input-field col s12 m12 l12">
				<i class="material-icons prefix">person</i>
				<%= f.text_field :name  %>
				<label for="user_name">Name</label>
			</div>

			<div class="input-field col s12 m12 l12">
				<i class="material-icons prefix">email</i>
				<%= f.text_field :email  %>
				<label for="user_email">E-mail</label>
			</div>

			<div class="input-field col s12 m12 l12">
				<i class="material-icons prefix">phone</i>
				<%= f.text_field :phone, :onkeypress => "mascara(this, checaTelefone)", maxlength: 15  %>
				<label for="user_phone">Phone</label>
			</div>

			<div class="input-field col s12 m12 l12">
				<i class="material-icons prefix">lock</i>
				<%= f.password_field :password   %>
				<label for="user_password" class="active">Password</label>
			</div>
			<div class="action  ">
				<button type="submit" class="send btn shadow green dark small right">Save</button>
			</div>
		</div>
<% end %>
</div>

app/views/dashboard/pages/settings.html.erb
<div class="container">
	<div class="row">
		<div class="col s12 m12 l12">
			<div class="layout">
				<span class="span f12">
				Use <br>
				@user for the username. Eg.: Welcome <strong class="grey-text text-darken-2">@user</strong> will become Welcome <strong class="grey-text text-darken-2"> <%= current_user.name %></strong><br>
				@cycle for cycle name <br>
				@test for test name (activity from cycle)
				</span>
		
			</div>
		</div>
		<div class="col s12 m12 l12">
			<div class="row">
				<%= form_for dashboard_save_settings_path, method: :post, url: dashboard_save_settings_path, remote: true do |f| %>

					<div class="field">
						<div class="input-field col s12">
							<p>Title - Confirmation</p>
							<%= f.text_field :email_confirmation_commitment_subject, name: :email_confirmation_commitment_subject, value: Setting.email_confirmation_commitment_subject %>
						</div>
					</div>
					<div class="field">
						<div class="input-field col s12">
						<p>Confirmation E-mail of Commitment to Cycle</p>
        				<%= f.cktext_area :email_confirmation_commitment, name: :email_confirmation_commitment, as: :text, ckeditor: {language: 'pt'}, value: Setting.email_confirmation_commitment %>
						</div>
					</div>

					<div class="field">
						<div class="input-field col s12">
							<p>Title - Task Completed</p>
							<%= f.text_field :email_activity_completion_subject, name: :email_activity_completion_subject, value: Setting.email_activity_completion_subject %>
						</div>
					</div>
					<div class="field">
						<div class="input-field col s12">
						<p>Task Completed E-mail</p>
        				<%= f.cktext_area :email_activity_completion, name: :email_activity_completion, as: :text, ckeditor: {language: 'pt'}, value: Setting.email_activity_completion %>
						</div>
					</div>


					<div class="field">
						<div class="input-field col s12">
							<p>Title - Deadline coming to end</p>
							<%= f.text_field :email_activity_deadline_coming_end_subject, name: :email_activity_deadline_coming_end_subject, value: Setting.email_activity_deadline_coming_end_subject %>
						</div>
					</div>
					<div class="field">
						<div class="input-field col s12">
						<p>E-mail Task deadline coming to end</p>
        				<%= f.cktext_area :email_activity_deadline_coming_end, name: :email_activity_deadline_coming_end, as: :text, ckeditor: {language: 'pt'}, value: Setting.email_activity_deadline_coming_end %>
						</div>
					</div>


					<div class="action  ">
						<button type="submit" class="send btn shadow green dark small right">Save</button>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>